const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ---- Musashi C sources (compiled via zig cc) --------------------------
    // m68kops.c/.h are generated by m68kmake from m68k_in.c. They are vendored
    // pre-generated for reproducibility (regenerate with: cd vendor/musashi &&
    // zig cc -o m68kmake m68kmake.c && ./m68kmake).
    const musashi_flags = [_][]const u8{
        "-std=gnu11",
        "-fno-sanitize=undefined",
        // Use our 68010 config.
        "-DMUSASHI_CNF=\"m68kconf.h\"",
    };

    const root = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    root.addIncludePath(b.path("vendor/musashi"));
    root.addIncludePath(b.path("vendor/musashi/softfloat"));

    // C interop: translate the Musashi public API into a Zig module named
    // "musashi" (replaces the old @cImport).
    const translate = b.addTranslateC(.{
        .root_source_file = b.path("src/musashi_c.h"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    translate.addIncludePath(b.path("vendor/musashi"));
    translate.addIncludePath(b.path("vendor/musashi/softfloat"));
    root.addImport("musashi", translate.createModule());
    root.addCSourceFiles(.{
        .root = b.path("vendor/musashi"),
        .files = &.{
            "m68kcpu.c",
            "m68kdasm.c",
            "m68kops.c",
            "softfloat/softfloat.c",
        },
        .flags = &musashi_flags,
    });
    root.addCSourceFile(.{ .file = b.path("src/host_stat.c"), .flags = &.{"-std=gnu11"} });
    root.addCSourceFile(.{ .file = b.path("src/host_dir.c"), .flags = &.{"-std=gnu11"} });
    root.link_libc = true;

    const exe = b.addExecutable(.{
        .name = "runupc",
        .root_module = root,
    });

    // Install per-target so cross-builds don't clobber each other:
    //   zig-out/bin/<arch>-<os>/runupc
    const res = target.result;
    const exe_name = if (res.os.tag == .windows) "runupc.exe" else "runupc";
    const dest_sub_path = b.fmt("{s}-{s}/{s}", .{ @tagName(res.cpu.arch), @tagName(res.os.tag), exe_name });
    const install_exe = b.addInstallArtifact(exe, .{
        .dest_sub_path = dest_sub_path,
        .pdb_dir = .disabled, // keep bin/ tidy; no stray .pdb at the root
    });
    b.getInstallStep().dependOn(&install_exe.step);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(&install_exe.step);
    // Forward extra CLI args after `--` to the emulator, when supported.
    if (@hasField(std.Build, "args")) {
        if (@field(b, "args")) |args| run_cmd.addArgs(args);
    }
    const run_step = b.step("run", "Run the emulator");
    run_step.dependOn(&run_cmd.step);

    // ---- Unit tests -------------------------------------------------------
    const test_step = b.step("test", "Run unit tests");

    // Pure-Zig tests (no C deps).
    for ([_][]const u8{ "src/abi.zig", "src/shlib.zig", "src/mem.zig", "src/coff.zig", "src/process.zig" }) |src| {
        const t = b.addTest(.{
            .root_module = b.createModule(.{
                .root_source_file = b.path(src),
                .target = target,
                .optimize = optimize,
            }),
        });
        test_step.dependOn(&b.addRunArtifact(t).step);
    }

    // fs.zig test: uses libc (open/read/...) but not the Musashi core.
    const fs_test_mod = b.createModule(.{
        .root_source_file = b.path("src/fs.zig"),
        .target = target,
        .optimize = optimize,
    });
    fs_test_mod.addCSourceFile(.{ .file = b.path("src/host_stat.c"), .flags = &.{"-std=gnu11"} });
    fs_test_mod.addCSourceFile(.{ .file = b.path("src/host_dir.c"), .flags = &.{"-std=gnu11"} });
    fs_test_mod.link_libc = true;
    const fs_test = b.addTest(.{ .root_module = fs_test_mod });
    test_step.dependOn(&b.addRunArtifact(fs_test).step);

    // procmodel.zig test: libc (fork/wait externs) + host_stat.c; the test
    // itself only checks status encoding (no actual fork). Musashi needed
    // because procmodel imports cpu/coff transitively.
    const pm_mod = b.createModule(.{
        .root_source_file = b.path("src/procmodel.zig"),
        .target = target,
        .optimize = optimize,
    });
    pm_mod.addIncludePath(b.path("vendor/musashi"));
    pm_mod.addIncludePath(b.path("vendor/musashi/softfloat"));
    pm_mod.addCSourceFiles(.{
        .root = b.path("vendor/musashi"),
        .files = &.{ "m68kcpu.c", "m68kdasm.c", "m68kops.c", "softfloat/softfloat.c" },
        .flags = &musashi_flags,
    });
    pm_mod.addCSourceFile(.{ .file = b.path("src/host_stat.c"), .flags = &.{"-std=gnu11"} });
    pm_mod.addCSourceFile(.{ .file = b.path("src/host_dir.c"), .flags = &.{"-std=gnu11"} });
    pm_mod.link_libc = true;
    const pm_tr = b.addTranslateC(.{
        .root_source_file = b.path("src/musashi_c.h"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    pm_tr.addIncludePath(b.path("vendor/musashi"));
    pm_tr.addIncludePath(b.path("vendor/musashi/softfloat"));
    pm_mod.addImport("musashi", pm_tr.createModule());
    const pm_test = b.addTest(.{ .root_module = pm_mod });
    test_step.dependOn(&b.addRunArtifact(pm_test).step);

    // cpu.zig test: needs the Musashi C core + translated module.
    const cpu_test_mod = b.createModule(.{
        .root_source_file = b.path("src/cpu_test.zig"),
        .target = target,
        .optimize = optimize,
    });
    cpu_test_mod.addIncludePath(b.path("vendor/musashi"));
    cpu_test_mod.addIncludePath(b.path("vendor/musashi/softfloat"));
    cpu_test_mod.addCSourceFiles(.{
        .root = b.path("vendor/musashi"),
        .files = &.{ "m68kcpu.c", "m68kdasm.c", "m68kops.c", "softfloat/softfloat.c" },
        .flags = &musashi_flags,
    });
    cpu_test_mod.link_libc = true;
    const cpu_translate = b.addTranslateC(.{
        .root_source_file = b.path("src/musashi_c.h"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    cpu_translate.addIncludePath(b.path("vendor/musashi"));
    cpu_translate.addIncludePath(b.path("vendor/musashi/softfloat"));
    cpu_test_mod.addImport("musashi", cpu_translate.createModule());
    const cpu_test = b.addTest(.{ .root_module = cpu_test_mod });
    test_step.dependOn(&b.addRunArtifact(cpu_test).step);

    // C-linked tests (execute guest code, need the Musashi core + module).
    for ([_][]const u8{ "src/runloop.zig", "src/syscalls.zig" }) |src| {
        const m = b.createModule(.{
            .root_source_file = b.path(src),
            .target = target,
            .optimize = optimize,
        });
        m.addIncludePath(b.path("vendor/musashi"));
        m.addIncludePath(b.path("vendor/musashi/softfloat"));
        m.addCSourceFiles(.{
            .root = b.path("vendor/musashi"),
            .files = &.{ "m68kcpu.c", "m68kdasm.c", "m68kops.c", "softfloat/softfloat.c" },
            .flags = &musashi_flags,
        });
        m.addCSourceFile(.{ .file = b.path("src/host_stat.c"), .flags = &.{"-std=gnu11"} });
        m.addCSourceFile(.{ .file = b.path("src/host_dir.c"), .flags = &.{"-std=gnu11"} });
        m.link_libc = true;
        const tr = b.addTranslateC(.{
            .root_source_file = b.path("src/musashi_c.h"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        tr.addIncludePath(b.path("vendor/musashi"));
        tr.addIncludePath(b.path("vendor/musashi/softfloat"));
        m.addImport("musashi", tr.createModule());
        const t = b.addTest(.{ .root_module = m });
        test_step.dependOn(&b.addRunArtifact(t).step);
    }
}
